version: "2.4"

services:
  http:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ${PWD}/example/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/example/stream.js:/usr/share/nginx/html/stream.js:ro
  http2:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ${PWD}/example/nginx2.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/example/index.html:/usr/share/nginx/html/index.html:ro
