

services:

  http:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/index.html:/usr/share/nginx/html/index.html:ro
